CREATE USER musiccatalog@localhost identified BY '1234';
GRANT usage ON *.* TO musiccatalog@localhost identified BY '1234';
CREATE DATABASE IF NOT EXISTS mc;
GRANT ALL privileges ON mc.* TO musiccatalog@localhost;
USE mc;
CREATE TABLE SONGS(
    SONG_ID INT NOT NULL auto_increment,
    NAME VARCHAR(50) NOT NULL,
    ALBUMID INT NOT NULL,
    ARTISTID INT NOT NULL,
    SOURCE VARCHAR(200) NOT NULL,
    PRIMARY KEY (SONG_ID)
);

CREATE TABLE ALBUMS(
    AlBUM_ID INT NOT NULL auto_increment,
    NAME VARCHAR(50) NOT NULL,
    YEAR INT NOT NULL,
    ARTISTID INT NOT NULL,
    COVERSOURCE VARCHAR(200) NOT NULL,
    PRIMARY KEY (AlBUM_ID)
);


CREATE TABLE ARTISTS(
    ARTIST_ID INT NOT NULL auto_increment,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ARTIST_ID)
);